Swap `?` placeholder and `_` wildcard using kind-projector 0.13.0 & scalac 2.13.6 (#1479)
* Use custom scala version

* Use `-Xsource:3`

* Use kind-projector `underscore-placeholders`

* Swap ? and _ with new kind-projector & `-Xsource:3`

* Workaround `scala.reflect.internal.FatalError:[error]   NoSymbol.clone()` error that happens on `Universe with Singleton` matches on 2.13.6-SNAPSHOT

* regenerate build

* `-Xsource:3` fixes

* Add 2.12 support

* Update to Scala 2.13.6

* Return older implementations without FatalError

* Add `nowarn`s for https://github.com/scala/bug/issues/12398

* Update to Scala 2.12.14

* fix build

* fix build

* regenerate build

* Fix regression introduced in `Return older implementations without FatalError`

* Fix unintended `?`->`_` replacements

* remove remaining `*` placeholders

* Disable `-Xsource:3` in docs due to mdoc failures:

```
error: basics.md:97 (mdoc generated code) could not find implicit value for parameter t: pprint.TPrint[zio.ZIO[zio.Has[zio.console.Console.Service],Throwable,β$0$]]
val injector: Injector[RIO[Console, _]] = Injector[RIO[Console, _]](); $doc.binder(injector, 2, 4, 2, 12)
                                                                                  ^

error: basics.md:109 (mdoc generated code) could not find implicit value for parameter t: pprint.TPrint[zio.ZIO[zio.Has[zio.console.Console.Service],Throwable,β$0$]]
val resource = injector.produce(plan); $doc.binder(resource, 4, 4, 4, 12)
                                                  ^

error: basics.md:1359 (mdoc generated code) could not find implicit value for parameter t: pprint.TPrint[zio.ZIO[zio.Has[zio.console.Console.Service],Throwable,β$9$]]
val res51 = chooseInterpreters(true); $doc.binder(res51, 26, 0, 26, 24)
```

* Enable -Xsource:3 in unidoc after disabling in mdoc